services:
  app:
    image: ${DOCKER_IMAGE}:dev
    container_name: ${APPLICATION_NAME}
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env
    ports:
      - "${SERVICE_PORT}:8086"
    networks:
      - external-net
    depends_on:
      - db
    restart: always
  # db 컨테이너만 실행 : docker compose up -d db
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - external-net

volumes:
  mysql_data:

networks:
  external-net:
    external: true
    name: ${MMB_DOCKER_NETWORK}