spring:
  application:
    name: ${APPLICATION_NAME:mmb-question-service}

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${CONTAINER_DB_PORT:3310}/${DB_NAME:demo_db}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:demo_user}
    password: ${DB_PASSWORD:demo_password}

  jpa:
    hibernate:
      ddl-auto: update # (처음에는 update로. 나중에는 validate로 변경 권장)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port:
    ${SERVICE_PORT:8080}

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}  %-5level --- [%X{APPLICATION_NAME}] [traceId=%X{traceId:-}, spanId=%X{spanId:-}] %logger{36} : %msg%n"
  level:
    root: info

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:mmb-zipkin}:${CONTAINER_ZIPKIN_PORT:9411}/api/v2/spans
